# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Exhibit.create(entry_code: "01", category: "Magazine Advertising Campaign", entry_name: "Gems and Minerals", entrant_name: "Kelsey Tiberi", entrant_company: "Ron Foth Advertising", vote_count: 0)
Exhibit.create(entry_code: "02", category: "Cinematography, Sound Design", entry_name: "Leap Deep", entrant_name: "Kelsey Tiberi", entrant_company: "Ron Foth Advertising", vote_count: 0)
Exhibit.create(entry_code: "03", category: "Animation, Special Effects or Motion Graphics", entry_name: "Wildlights", entrant_name: "Kelsey Tiberi", entrant_company: "Ron Foth Advertising", vote_count: 0)
Exhibit.create(entry_code: "04", category: "Digital Creative Technology", entry_name: "A Plant's Eye View", entrant_name: "Matthew Mohr", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "05", category: "Art Direction", entry_name: "Anthropologie: Tis the Season", entrant_name: "James Lutz", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "06", category: "Packaging", entry_name: "Black Ivory", entrant_name: "Josh Bodman", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "07", category: "Advertising Industry Self-Promotion Direct Marketing & Specialty Items", entry_name: "Bonfire Red Candle Holiday Gift", entrant_name: "Joey Zornes", entrant_company: "Bonfire Red", vote_count: 0)
Exhibit.create(entry_code: "08", category: "Advertising Industry Self-Promotion Direct Marketing & Specialty Items", entry_name: "Calendar of Fun Holidays", entrant_name: "Matt Hoelter", entrant_company: "Pixel Park", vote_count: 0)
Exhibit.create(entry_code: "09", category: "Printed Annual Report", entry_name: "CBJ Foundation Impact Report", entrant_name: "Megan Myers", entrant_company: "treetree", vote_count: 0)
Exhibit.create(entry_code: "10", category: "Integrated Branded Content Campaign", entry_name: "CCAD 2016 Fashion Show", entrant_name: "Chelsea Castle", entrant_company: "Ologie", vote_count: 0)
Exhibit.create(entry_code: "11", category: "Brochure", entry_name: "CCAD 2016 Fashion Show Book", entrant_name: "Chelsea Castle", entrant_company: "Ologie", vote_count: 0)
Exhibit.create(entry_code: "12", category: "Film/Video/Sound Branded Content, More Than :60 Seconds", entry_name: "CCAD 2016 Fashion Show Video", entrant_name: "Chelsea Castle", entrant_company: "Ologie", vote_count: 0)
Exhibit.create(entry_code: "13", category: "Guerilla Marketing Campaign", entry_name: "Cincy Opening Day Guerilla Campaign", entrant_name: "Anthony Trimpe", entrant_company: "HOMAGE", vote_count: 0)
Exhibit.create(entry_code: "14", category: "Packaging, Illustration -- Campaign", entry_name: "Clif Bar", entrant_name: "Matthew Mohr", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "15", category: "Direct Mail Campaign", entry_name: "Denison University Admissions", entrant_name: "Chelsea Castle", entrant_company: "Ologie", vote_count: 0)
Exhibit.create(entry_code: "16", category: "Direct Mail", entry_name: "Denison University Viewbook", entrant_name: "Chelsea Castle", entrant_company: "Ologie", vote_count: 0)
Exhibit.create(entry_code: "17", category: "Art Direction, Packaging, Campaign, Color - Single", entry_name: "Grey Goose", entrant_name: "Matthew Mohr", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "18", category: "Illustration Series", entry_name: "Harvest of the Month Veggies", entrant_name: "Jenny Alberti", entrant_company: "amelia street studio", vote_count: 0)
Exhibit.create(entry_code: "19", category: "Online/Interactive Campaign", entry_name: "HOMAGE's AAHHH-MAZING Extravaganza!", entrant_name: "Anthony Trimpe", entrant_company: "HOMAGE", vote_count: 0)
Exhibit.create(entry_code: "20", category: "Illustration", entry_name: "Independents Day", entrant_name: "Elizabeth Stelzer", entrant_company: "GSW", vote_count: 0)
Exhibit.create(entry_code: "21", category: "Magazine Design", entry_name: "Industry West Magalog", entrant_name: "Erin Balow", entrant_company: "Fahlgren Mortine", vote_count: 0)
Exhibit.create(entry_code: "22", category: "Business-to-Business Website", entry_name: "JBAD Website", entrant_name: "Sebastian Ibel", entrant_company: "Ibel Agency", vote_count: 0)
Exhibit.create(entry_code: "23", category: "Advertising Industry Self-Promotion Print Advertising, Public Service Online/Interactive", entry_name: "Lilly Oncology On Canvas", entrant_name: "Elizabeth Stelzer", entrant_company: "GSW", vote_count: 0)
Exhibit.create(entry_code: "24", category: "S11A- Single Occurrence orf Installation", entry_name: "Metro Parks - Moss Art", entrant_name: "Matthew Mohr", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "25", category: "S26D - Campaign", entry_name: "Michaels Holiday Craft Guide", entrant_name: "Mark Burleigh", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "26", category: "Product or Service Sales Promotion Campaign", entry_name: "Monmouth University Brand Campaign", entrant_name: "Chelsea Castle", entrant_company: "Ologie", vote_count: 0)
Exhibit.create(entry_code: "27", category: "S07A - Single (Full Page or Less)", entry_name: "National Eating Disorders", entrant_name: "James Lutz", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "28", category: "Email", entry_name: "NBA 90s Pack Launch", entrant_name: "Anthony Trimpe", entrant_company: "HOMAGE", vote_count: 0)
Exhibit.create(entry_code: "29", category: "Online/Interactive Campaign", entry_name: "NBA 90s Throwback Campaign", entrant_name: "Anthony Trimpe", entrant_company: "HOMAGE", vote_count: 0)
Exhibit.create(entry_code: "30", category: "Multiple Events", entry_name: "Nestlé Toll House: Bake Some Good", entrant_name: "Amanda DeCastro", entrant_company: "Resource/Ammirati, An IBM Company", vote_count: 0)
Exhibit.create(entry_code: "31", category: "Sales Kit or Product Information Sheets", entry_name: "Netjets Web-to-Print Custom Books", entrant_name: "Joey Zornes", entrant_company: "Bonfire Red", vote_count: 0)
Exhibit.create(entry_code: "32", category: "Out-Of-Home Multiple Installations", entry_name: "ODW Logistics Office", entrant_name: "Casi Douglas", entrant_company: "TENFOLD", vote_count: 0)
Exhibit.create(entry_code: "33", category: "Poster, Advertising Industry Self-Promotion Ambient Media, Illustration", entry_name: "Ohio Creativity", entrant_name: "Elizabeth Stelzer", entrant_company: "GSW", vote_count: 0)
Exhibit.create(entry_code: "34", category: "Branded Content & Entertainment", entry_name: "Opening Day Guerilla Newspaper", entrant_name: "Anthony Trimpe", entrant_company: "HOMAGE", vote_count: 0)
Exhibit.create(entry_code: "35", category: "Film/Video/Sound Branded Content, More Than :60 Seconds, Public Service Online Film, Video & Sound", entry_name: "OSU Food Insecurity", entrant_name: "Michael Gillespie", entrant_company: "Spacejunk", vote_count: 0)
Exhibit.create(entry_code: "36", category: "Cinematography", entry_name: "PorterWright Holiday Video", entrant_name: "Timothy Flaherty", entrant_company: "Post House Creeative", vote_count: 0)
Exhibit.create(entry_code: "37", category: "Consumer Website", entry_name: "QS Partners Website", entrant_name: "Joey Zornes", entrant_company: "Bonfire Red", vote_count: 0)
Exhibit.create(entry_code: "38", category: "Out-Of-Home Multiple Installations", entry_name: "S-E-A Office", entrant_name: "Casi Douglas", entrant_company: "TENFOLD", vote_count: 0)
Exhibit.create(entry_code: "39", category: "Card, Invitation or Announcement Campaign", entry_name: "Scentsy Family Reunion", entrant_name: "Nicole Madsen", entrant_company: "Laine Gabriel", vote_count: 0)
Exhibit.create(entry_code: "40", category: "Out-Of-Home Multiple Installations", entry_name: "Seamless Logistics Office", entrant_name: "Casi Douglas", entrant_company: "TENFOLD", vote_count: 0)
Exhibit.create(entry_code: "41", category: "Branded Content & Entertainment Campaign", entry_name: "Stop StankFace", entrant_name: "Amanda DeCastro", entrant_company: "Resource/Ammirati, An IBM Company", vote_count: 0)
Exhibit.create(entry_code: "42", category: "Brochure", entry_name: "Sukiya Tokyo Bowls & Noodles", entrant_name: "Ansley Phillips", entrant_company: "WD Partners", vote_count: 0)
Exhibit.create(entry_code: "43", category: "Menu", entry_name: "Sukiya Tokyo Bowls & Noodles Menu", entrant_name: "Ansley Phillips", entrant_company: "WD Partners", vote_count: 0)
Exhibit.create(entry_code: "44", category: "Stationary Package - Single or Multiple pieces, Integrated Brand Identity Campaign", entry_name: "Super Eight Brand Identity Campaign", entrant_name: "Matthew Mohr", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "45", category: "Advertisting Industry Self-Promotion Film/Video/Sound", entry_name: "Super77 Showreel", entrant_name: "Chavilah Bennett", entrant_company: "Super77", vote_count: 0)
Exhibit.create(entry_code: "46", category: "S05C - Cover/Editorial Spread or Feature - Series", entry_name: "The Black Book", entrant_name: "James Lutz", entrant_company: "Columbus College of Art & Design", vote_count: 0)
Exhibit.create(entry_code: "47", category: "Poster", entry_name: "The Science and Art of Empathy", entrant_name: "Elizabeth Stelzer", entrant_company: "GSW", vote_count: 0)
Exhibit.create(entry_code: "48", category: "Public Service Brochure/Sales Kit", entry_name: "THIS IS HUNGER", entrant_name: "Adma Dabilis", entrant_company: "Mid-Ohio Foodbank", vote_count: 0)
Exhibit.create(entry_code: "49", category: "Copywriting", entry_name: "TidyCats Microsite", entrant_name: "Amanda DeCastro", entrant_company: "Resource/Ammirati, An IBM Company", vote_count: 0)
Exhibit.create(entry_code: "50", category: "Online/Interactive Campaign", entry_name: "TidyLock Campaign", entrant_name: "Amanda DeCastro", entrant_company: "Resource/Ammirati, An IBM Company", vote_count: 0)
Exhibit.create(entry_code: "51", category: "Consumer Website", entry_name: "Title Boxing Club", entrant_name: "Zach Gerber", entrant_company: "Mindstream Interactive", vote_count: 0)
Exhibit.create(entry_code: "52", category: "Direct Mail 3-D/Mixed", entry_name: "Trailer Full of Donuts", entrant_name: "Daren Elosh", entrant_company: "Sync", vote_count: 0)
Exhibit.create(entry_code: "53", category: "Cinematography", entry_name: "treetree Agency of Special Projects", entrant_name: "Timothy Flaherty", entrant_company: "Post House Creative", vote_count: 0)
Exhibit.create(entry_code: "54", category: "Film/Video/Sound Branded Content, :60 Seconds or Less", entry_name: "treetree brand video", entrant_name: "Megan Myers", entrant_company: "treetree", vote_count: 0)
Exhibit.create(entry_code: "55", category: "Direct Mail 3-D/Mixed", entry_name: "treetree Share the Love Valentine", entrant_name: "Megan Myers", entrant_company: "treetree", vote_count: 0)
Exhibit.create(entry_code: "56", category: "Business-to-Business Website, Copywriting", entry_name: "treetree website", entrant_name: "Megan Myers", entrant_company: "treetree", vote_count: 0)
Exhibit.create(entry_code: "57", category: "Direct Mail, Magazine Advertising - Full Page or Less, Integrated Branded Content Campaign", entry_name: "University at Buffalo BrandCampaign", entrant_name: "Chelsea Castle", entrant_company: "Ologie", vote_count: 0)
Exhibit.create(entry_code: "58", category: "Packaging", entry_name: "Vim & Petal", entrant_name: "Chelsea Castle", entrant_company: "Ologie", vote_count: 0)
Exhibit.create(entry_code: "59", category: "Film/Video/Sound Branded Content, More Than :60 Seconds, Copywriting", entry_name: "White Castle: Choose Your Adventure", entrant_name: "Amanda DeCastro", entrant_company: "Resource/Ammirati, An IBM Company", vote_count: 0)
Exhibit.create(entry_code: "60", category: "Advertising Industry Self-Promotion Online/Interactive", entry_name: "ZoCo Design Website", entrant_name: "Lacy Picazo", entrant_company: "ZoCo Design", vote_count: 0)
